### ISSUE TITLE
Module 'CTPanoramaView' not found

### ISSUE THREAD

**Issue by xioozq** [lightbasenl/react-native-panorama-view#1]
ios:
Module 'CTPanoramaView' not found
in PanoramaView.h

and react-native link has been successfully

**Comment by rodymolenaar** [comment]
Hi,

Can you make sure to follow these steps: https://github.com/lightbasenl/react-native-panorama-view#manual-installation

If you've done that and are still experiencing this issue, please attach your Podfile so I can help you better :)

**Comment by xioozq** [comment]
> Hi,
> 
> Can you make sure to follow these steps: https://github.com/lightbasenl/react-native-panorama-view#troubleshooting-ios
> 
> If you've done that and are still experiencing this issue, please attach your Podfile so I can help you better :)

thanks, now build successfully, but a  new problem "This copy of libswiftCore.dylib requires an OS version prior to 12.2.0. " when I runing at simulator or XS Real machine.

**Comment by rodymolenaar** [comment]
@xioozq This might be related to https://stackoverflow.com/questions/55361057/this-copy-of-libswiftcore-dylib-requires-an-os-version-prior-to-12-2-0

Could you make sure you followed those steps exactly?
Otherwise please share your Runpath Search Paths in Xcode :)

**Comment by xioozq** [comment]
@rodymolenaar  I made a mistake on "Runpath Search Paths",  it's ok now 😂
