### ISSUE TITLE
GoogleMaps 360 Streetview

### ISSUE THREAD

**Issue by Alaaeldin-as1405124** [lightbasenl/react-native-panorama-view#12]
Can we get 360 degree images from google maps using lat. & longitude, and display it? I tried to copy the link but it seems that this feature isn't supported

**Comment by rodymolenaar** [comment]
I'm sorry, what are you exactly trying to do?

**Comment by Alaaeldin-as1405124** [comment]
I'm trying to get google street view image link and put it into the imageUrl prop, for example 

https://www.google.com/maps/place/Alfardan+Automobiles/@25.2839568,51.5063996,3a,75y,140h,90t/data=!3m8!1e1!3m6!1sAF1QipMJHOmYf_K-VWr8guvvIhLuD_UP_6VTVTJzajBK!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipMJHOmYf_K-VWr8guvvIhLuD_UP_6VTVTJzajBK%3Dw211-h120-k-no-pi-10-ya304.4-ro0-fo100!7i6316!8i3158!4m8!1m2!2m1!1sbmw+showroom+qatar!3m4!1s0x3e45dacfa4c79d93:0xab85b589cbc9eed4!8m2!3d25.2839568!4d51.5063996

So i'm asking if we can include this feature in the library, not using image url only, but latitude, longitude and fetch those panorama images from google directly.

**Comment by rodymolenaar** [comment]
This is a bit out of scope for this package, maybe you can find yourself a solution that generates panoramic images from Google Maps, which you can use with this library, but you'd also have to deal with copyright and the likes.
