### ISSUE TITLE
Module "CTPanoramaView" not found in PanoramaView.h file

### ISSUE THREAD

**Issue by softerboy** [lightbasenl/react-native-panorama-view#14]
.../node_modules/@lightbase/react-native-panorama-view/ios/PanoramaViewManager.m:9:9: In file included from .../node_modules/@lightbase/react-native-panorama-view/ios/PanoramaViewManager.m:9:

Platform:
  1. XCode Version 11.0 (11A420a)
  2. React Native 0.59.8

**Comment by rodymolenaar** [comment]
Hi there!

Have you follows the iOS troubleshooting section of the readme?

**Comment by softerboy** [comment]
Hi @rodymolenaar.

Problem was on pod file.
I commented out use_frameworks! and all is worked fine
