### ISSUE TITLE
Is it possible to use it in a Expo app not ejected ?

### ISSUE THREAD

**Issue by pierol** [lightbasenl/react-native-panorama-view#15]
Hi, and thank you for sharing this component. My question is if it is possible to use it in a sytandard Expo app not ejected ?

**Comment by rodymolenaar** [comment]
I'm not sure, I've never really worked with Expo. I'm a bit time constrained currently, so I won't be looking into it anytime soon. But feel free to report back if you learn more.

**Comment by pierol** [comment]
Thank you anyway for your answer. I'm trying the solution with GLView of expo with no success at the moment and  suggested here on stakoverflow https://stackoverflow.com/questions/48595078/how-to-show-360-images-in-the-react-native/48595931.
If i fail i will try with your component, but i think i've to ejected the project for make the linking and the pods install as you suggest in Automatic Installation.

Thank you anyway
