### ISSUE TITLE
Invariant Violation: requireNativeComponent: "PanoramaView" was not found in the UIManager. 

### ISSUE THREAD

**Issue by wanghhh** [lightbasenl/react-native-panorama-view#21]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/12121627/69301306-c2013f00-0c50-11ea-864f-7381a8a91b7b.png">

**Comment by wanghhh** [comment]
According to the author's instructions in the readme, it is already ok.

**Comment by jasonHav** [comment]
@wanghhh I'm having the same issue here, what did you end up changing to make it work?
I'm trying to embed a panorama in a storybook.

**Comment by samor412** [comment]
@wanghhh I'm having the same issue as well. Do you have any solution

**Comment by SumaPrajapati** [comment]
Even i am having the same issue. Pls try to resolve this issue.
