### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by MartinCura** [lightbasenl/react-native-panorama-view#24]
Hi there!

I don't know how maintained this is nowadays. Are there any plans to have a **VideoView**, to display an equirectangular video as a sphere around the camera? If not, do you know how difficult it'd be to add it myself?

If i'm not mistaken this project relies on Google VR (deprecated for Cardboard?) and CTPanoramaView, and i'm not sure whether the last one has support for video.

Thanks!

**Comment by rodymolenaar** [comment]
Hi,

We don't have plans to add a VideoView ourselves currently. 

A big part in determining the difficulty would be wether you can find libraries that support this functionality for both iOS and Android. Writing a native wrapper itself is quite straightforward if you find the right documentation.

From my understanding CTPanoramaView doesn't have video support and is also missing some other Google VR functionality.

I hope this points you in the right direction.

**Comment by MartinCura** [comment]
Thanks! I'm trying with [ViroReact](https://github.com/viromedia/viro) for lack of a better option.
