### ISSUE TITLE
 API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'

### ISSUE THREAD

**Issue by Waheed-Rumaneh** [lightbasenl/react-native-panorama-view#39]
API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()' and when i replace it with 
javaCompileProvider and javaCompileProvider .get() it's return this error :

error: package android.support.annotation does not exist

cannot find symbol
    public @Nullable Map getExportedCustomDirectEventTypeConstants()

cannot find symbol
    private void emitEvent(String name, @Nullable WritableMap event)

**Comment by Waheed-Rumaneh** [comment]
Solved

**Comment by itseramin** [comment]
Care to explain how?
