### ISSUE TITLE
problem downloading with NPM/YARN

### ISSUE THREAD

**Issue by mimmobordini** [lightbasenl/react-native-panorama-view#4]
i'm trying to download via npm this project, but it says E404 not found. is this project still avaliable?

**Comment by tonyt85** [comment]
I have the same problem trying to install using npm or yarn

**Comment by maslhiro** [comment]
try add this code in dependencies , sorry my bad english 😢 
` "react-native-panorama-view":"git+https://github.com/lightbasenl/react-native-panorama-view"`

**Comment by rodymolenaar** [comment]
I'll try and find some time to investigate these issues today

**Comment by rodymolenaar** [comment]
Please refer to #2 for further discussion and possible solutions
