### ISSUE TITLE
iOS build fails if request type is optional 

### ISSUE THREAD

**Issue by owinter86** [lightbasenl/react-native-panorama-view#60]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@lightbase/react-native-panorama-view@1.0.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@lightbase/react-native-panorama-view/ios/PanoramaView.swift b/node_modules/@lightbase/react-native-panorama-view/ios/PanoramaView.swift
index 09309f1..c5d0570 100644
--- a/node_modules/@lightbase/react-native-panorama-view/ios/PanoramaView.swift
+++ b/node_modules/@lightbase/react-native-panorama-view/ios/PanoramaView.swift
@@ -40,7 +40,7 @@ import Foundation
                 self.cancel?()
                 self.cancel = nil
                 
-                self.cancel = loader.loadImage(with: request, callback: { (error, image) in
+                self.cancel = loader.loadImage(with: request!, callback: { (error, image) in
                     
                     DispatchQueue.main.async {
                         
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by LuuchoRocha** [comment]
Thanks for the workaround. I'm experiencing the same issue

**Comment by cristianoccazinsp** [comment]
Why would request be optional? I'm not getting any build errors, is this an issue with RN 0.64 ?

**Comment by LuuchoRocha** [comment]
@cristianoccazinsp Yes, I'm experiencing this issue with 0.64.2. Using latest XCode on big sour, targeting iOS >= 13

**Comment by cristianoccazinsp** [comment]
Strange, when I test the change it builds with and without the extra ! as that call is bridged between objc and swift. I’m using RN 0.62 so perhaps they changed something there.

**Comment by cristianoccazinsp** [comment]
Fixed in https://github.com/lightbasenl/react-native-panorama-view/pull/67

Looks like this became an issue after RN 0.63 or above.
